//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IconRecruitmentTest.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IconRecruitmentTest.Common.Resources.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred! Please try again!.
        /// </summary>
        public static string AnErrorOccurredPleaseTryAgain {
            get {
                return ResourceManager.GetString("AnErrorOccurredPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on dimensions:.
        /// </summary>
        public static string BasedOnDimensions {
            get {
                return ResourceManager.GetString("BasedOnDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on weight:.
        /// </summary>
        public static string BasedOnWeight {
            get {
                return ResourceManager.GetString("BasedOnWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate price.
        /// </summary>
        public static string CalculatePrice {
            get {
                return ResourceManager.GetString("CalculatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total volume should be less than 2000cm3&lt;/br&gt; Calculated  width x height x  depth.
        /// </summary>
        public static string Cargo4YouValidationDimension {
            get {
                return ResourceManager.GetString("Cargo4YouValidationDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight should be less than 20Kg.
        /// </summary>
        public static string Cargo4YouValidationWeight {
            get {
                return ResourceManager.GetString("Cargo4YouValidationWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 1000cm3 and &lt;= 1700cm3 costs €21.99.
        /// </summary>
        public static string Dimensions_Between_1000cm_and_1700cm {
            get {
                return ResourceManager.GetString("Dimensions_Between_1000cm_and_1700cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 1000cm3 and &lt;= 2000cm3 costs €20.
        /// </summary>
        public static string Dimensions_Between_1000cm_and_2000cm {
            get {
                return ResourceManager.GetString("Dimensions_Between_1000cm_and_2000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 2000cm3 and &lt;= 5000cm3 costs €48.50.
        /// </summary>
        public static string Dimensions_Between_2000cm_and_5000cm {
            get {
                return ResourceManager.GetString("Dimensions_Between_2000cm_and_5000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &lt;= 1000cm3 costs €10.
        /// </summary>
        public static string Dimensions_Less_Than_1000cm {
            get {
                return ResourceManager.GetString("Dimensions_Less_Than_1000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 5000cm3 costs €147.50.
        /// </summary>
        public static string Dimensions_Over_5000cm {
            get {
                return ResourceManager.GetString("Dimensions_Over_5000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LogisticsCompany {
            get {
                return ResourceManager.GetString("LogisticsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total volume should be greater than 500cm3&lt;/br&gt; Calculated width x height x  depth.
        /// </summary>
        public static string MaltaShipValidationDimension {
            get {
                return ResourceManager.GetString("MaltaShipValidationDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight should be greater than 10Kg.
        /// </summary>
        public static string MaltaShipValidationWeight {
            get {
                return ResourceManager.GetString("MaltaShipValidationWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 1000cm3 and &lt;= 2000cm3 costs €19.50.
        /// </summary>
        public static string MSHDimensions_Between_1000cm_and_2000cm {
            get {
                return ResourceManager.GetString("MSHDimensions_Between_1000cm_and_2000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &lt;= 1000cm3 costs €9.50.
        /// </summary>
        public static string MSHDimensions_Less_Than_1000cm {
            get {
                return ResourceManager.GetString("MSHDimensions_Less_Than_1000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 10Kg and &lt;= 20Kg costs €16.99.
        /// </summary>
        public static string MSHWeight_Between_10kg_and_20kg {
            get {
                return ResourceManager.GetString("MSHWeight_Between_10kg_and_20kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No info.
        /// </summary>
        public static string NoInfo {
            get {
                return ResourceManager.GetString("NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your.
        /// </summary>
        public static string PleaseEnterYour {
            get {
                return ResourceManager.GetString("PleaseEnterYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send shipping.
        /// </summary>
        public static string SendShipping {
            get {
                return ResourceManager.GetString("SendShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the dimensions:.
        /// </summary>
        public static string SetTheDimensions {
            get {
                return ResourceManager.GetString("SetTheDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the weight:.
        /// </summary>
        public static string SetTheWeight {
            get {
                return ResourceManager.GetString("SetTheWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &lt;= 1000cm3 costs €11.99.
        /// </summary>
        public static string SHF_Dimensions_Less_Than_1000cm {
            get {
                return ResourceManager.GetString("SHF_Dimensions_Less_Than_1000cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total volume should be less than 1700cm3&lt;/br&gt; Calculated width x height x  depth.
        /// </summary>
        public static string ShipFasterValidationDimension {
            get {
                return ResourceManager.GetString("ShipFasterValidationDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight should be between 10Kg and 30kg.
        /// </summary>
        public static string ShipFasterValidationWeight {
            get {
                return ResourceManager.GetString("ShipFasterValidationWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping activities based on number of orders.
        /// </summary>
        public static string ShippingActivitiesBasedOnNumberOfOrders {
            get {
                return ResourceManager.GetString("ShippingActivitiesBasedOnNumberOfOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping activities based on total price.
        /// </summary>
        public static string ShippingActivitiesBasedOnTotalPrice {
            get {
                return ResourceManager.GetString("ShippingActivitiesBasedOnTotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total calculated:.
        /// </summary>
        public static string TotalCalculated {
            get {
                return ResourceManager.GetString("TotalCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is incorrect!.
        /// </summary>
        public static string UsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 10Kg and &lt;= 15Kg costs €16.50.
        /// </summary>
        public static string Weight_Between_10kg_and_15kg {
            get {
                return ResourceManager.GetString("Weight_Between_10kg_and_15kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 15Kg and &lt;= 25Kg costs €36.50.
        /// </summary>
        public static string Weight_Between_15kg_and_25kg {
            get {
                return ResourceManager.GetString("Weight_Between_15kg_and_25kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 20Kg and &lt;= 30Kg costs €33.99.
        /// </summary>
        public static string Weight_Between_20kg_and_30kg {
            get {
                return ResourceManager.GetString("Weight_Between_20kg_and_30kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 2Kg and &lt;= 15Kg costs €18.
        /// </summary>
        public static string Weight_Between_2kg_and_15kg {
            get {
                return ResourceManager.GetString("Weight_Between_2kg_and_15kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 15Kg and &lt;= 20Kg costs €35.
        /// </summary>
        public static string Weight_Between_Than_15kg_and_20kg {
            get {
                return ResourceManager.GetString("Weight_Between_Than_15kg_and_20kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &lt;= 2Kg costs €15.
        /// </summary>
        public static string Weight_Less_Than_2kg {
            get {
                return ResourceManager.GetString("Weight_Less_Than_2kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 25Kg costs €40 plus €0.417 for every Kg over 25Kg.
        /// </summary>
        public static string Weight_Over_25kg {
            get {
                return ResourceManager.GetString("Weight_Over_25kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any parcel &gt; 30Kg costs €43.99 plus €0.41 for every Kg over 25Kg.
        /// </summary>
        public static string Weight_Over_30kg {
            get {
                return ResourceManager.GetString("Weight_Over_30kg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width:.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
